package runtime

import (
	"crypto/sha256"
	"fmt"
)

// MockBackendWorkerAgent simulates a backend-specialized worker.
// It produces API specs, schema SQLs, and source code artifacts.
type MockBackendWorkerAgent struct{}

func (a *MockBackendWorkerAgent) Role() string           { return "worker" }
func (a *MockBackendWorkerAgent) Specialization() string { return "backend" }

func (a *MockBackendWorkerAgent) Execute(input *AgentTaskInput) (*AgentTaskOutput, error) {
	if input.Task == nil {
		return &AgentTaskOutput{Status: OutputStatusFailed, Error: "backend worker requires task context"}, nil
	}

	task := input.Task
	content := fmt.Sprintf(`package handler

// Auto-generated by Backend Worker Agent
// Task: %s
// Description: %s

import "net/http"

func Handle%s(w http.ResponseWriter, r *http.Request) {
	// TODO: implement
	w.WriteHeader(http.StatusOK)
}
`, task.Title, task.Description, sanitizeFuncName(task.Title))

	checksum := fmt.Sprintf("%x", sha256.Sum256([]byte(content)))

	return &AgentTaskOutput{
		Status:  OutputStatusNeedsReview,
		Summary: fmt.Sprintf("后端任务「%s」已完成：生成 API handler 代码", task.Title),
		Artifacts: []ArtifactAction{
			{
				Name:         fmt.Sprintf("%s-后端实现", task.Title),
				ArtifactType: "source_code",
				Description:  fmt.Sprintf("任务「%s」的后端 API 实现代码", task.Title),
				URI:          fmt.Sprintf("mock://artifacts/%s/source_code", task.ID),
				ContentType:  "text/x-go",
				SizeBytes:    int64(len(content)),
				Content:      content,
				Metadata:     map[string]any{"checksum": checksum, "generator": "mock_backend_worker", "language": "go"},
			},
		},
		Handoffs: []HandoffAction{
			{
				Summary:        fmt.Sprintf("后端任务「%s」执行完成", task.Title),
				CompletedItems: []string{"API handler 代码已生成", "路由已注册"},
				PendingItems:   []string{"等待独立评审", "需前端联调"},
				Risks:          []string{"Mock 代码仅作骨架，业务逻辑需补充"},
				NextSteps:      []string{"提交评审", "前端对接"},
			},
		},
		Transitions: []TransitionAction{
			{TaskTitle: task.Title, NewStatus: "in_review"},
		},
	}, nil
}

func sanitizeFuncName(title string) string {
	result := make([]byte, 0, len(title))
	upper := true
	for _, r := range title {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' {
			if upper {
				if r >= 'a' && r <= 'z' {
					r -= 32
				}
				upper = false
			}
			result = append(result, byte(r))
		} else {
			upper = true
		}
	}
	if len(result) == 0 {
		return "Task"
	}
	return string(result)
}
