package runtime

import (
	"crypto/sha256"
	"fmt"
)

// MockFrontendWorkerAgent simulates a frontend-specialized worker.
// It produces React/TypeScript component artifacts.
type MockFrontendWorkerAgent struct{}

func (a *MockFrontendWorkerAgent) Role() string           { return "worker" }
func (a *MockFrontendWorkerAgent) Specialization() string { return "frontend" }

func (a *MockFrontendWorkerAgent) Execute(input *AgentTaskInput) (*AgentTaskOutput, error) {
	if input.Task == nil {
		return &AgentTaskOutput{Status: OutputStatusFailed, Error: "frontend worker requires task context"}, nil
	}

	task := input.Task
	componentName := sanitizeFuncName(task.Title)
	content := fmt.Sprintf(`"use client";

import React from "react";

// Auto-generated by Frontend Worker Agent
// Task: %s

interface %sProps {
  // TODO: define props
}

export default function %s({}: %sProps) {
  return (
    <div className="p-4">
      <h1 className="text-xl font-bold">%s</h1>
      <p className="text-gray-600">%s</p>
      {/* TODO: implement UI */}
    </div>
  );
}
`, task.Title, componentName, componentName, componentName, task.Title, task.Description)

	checksum := fmt.Sprintf("%x", sha256.Sum256([]byte(content)))

	return &AgentTaskOutput{
		Status:  OutputStatusNeedsReview,
		Summary: fmt.Sprintf("前端任务「%s」已完成：生成 React 组件", task.Title),
		Artifacts: []ArtifactAction{
			{
				Name:         fmt.Sprintf("%s-前端组件", task.Title),
				ArtifactType: "source_code",
				Description:  fmt.Sprintf("任务「%s」的前端 React 组件", task.Title),
				URI:          fmt.Sprintf("mock://artifacts/%s/source_code", task.ID),
				ContentType:  "text/typescript",
				SizeBytes:    int64(len(content)),
				Content:      content,
				Metadata:     map[string]any{"checksum": checksum, "generator": "mock_frontend_worker", "framework": "react"},
			},
		},
		Handoffs: []HandoffAction{
			{
				Summary:        fmt.Sprintf("前端任务「%s」执行完成", task.Title),
				CompletedItems: []string{"React 组件已生成", "TypeScript 类型已定义"},
				PendingItems:   []string{"等待独立评审", "需后端 API 联调"},
				Risks:          []string{"Mock 组件仅作骨架，交互逻辑需补充"},
				NextSteps:      []string{"提交评审", "后端对接"},
			},
		},
		Transitions: []TransitionAction{
			{TaskTitle: task.Title, NewStatus: "in_review"},
		},
	}, nil
}
